blank_issues_enabled: true
contact_links:
  - name: 请求修改或新增 CSL 样式
    url: https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl
    about: "在这里提交关于 CSL 样式本身的请求"

  - name: 提问、求助、好想法
    url: https://github.com/orgs/zotero-chinese/discussions/new/choose
    about: "前往 Discussion 参与讨论！"

  - name: QQ 群
    url: http://plugins.zotero-chinese.com/
    about: "在链接中查看 QQ 群号码"