name: ci-pr

on:
  #   pull_request:
  #     branches:
  #       - main
  workflow_dispatch:

jobs:
  upload:
    name: 上传运行信息
    runs-on: ubuntu-latest
    if: github.repository == 'zotero-chinese/styles' && github.event_name == 'pull_request'
    steps:
      - name: 保存 PR 编号
        run: |
          echo "${{ github.event.number }}" > pr_num
      - name: 上传 PR 编号
        uses: actions/upload-artifact@v4
        with:
          name: pr-num
          path: ./pr_num
