name: ci
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**'
  #     - 'lib/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist

      # - name: Commit
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     # default_author: github_actions
      #     add: "src"
      #     message: "Auto Build Preview"
      #     push: "--set-upstream origin main"
      #     committer_name: GitHub Actions
      #     committer_email: 41898282+github-actions[bot]@users.noreply.github.com
