name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: 同步到 Gitee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: northword/push-to-gitee-action@v0
        with:
          gitee_repo: git@gitee.com:zotero-chinese-x/styles.dev.git
          gitee_token: ${{ secrets.GITEE_PRIVATE_KEY }}
          files: "**/*.csl"
