name: ci
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'lib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          yarn install
          yarn run generate
          yarn run build:vite
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'src'
          message: 'Auto Build Preview'
          push: '--set-upstream origin main'