name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    name: 同步到 Gitee
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:zotero-chinese/styles.git" # github仓库地址
          destination-repo: "git@gitee.com:zotero-chinese-x/styles.git" # gitee仓库地址
