name: issue-bot

on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created, edited]
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  label:
    permissions:
      issues: write # to add label to an issues (retorquere/label-gun)
      pull-requests: write # to add label, comment on pull request (retorquere/label-gun)
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label.awaiting: "waiting-for-response-from-contributor"

  stable:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 60
          days-before-issue-close: -1
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale."
          exempt-issue-labels: "help wanted"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
